#!/usr/bin/env python3

# WARNING: CAVEAT UTILITOR
#
#  This file was automatically generated by TatSu.
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.

# ruff: noqa: C405, COM812, I001, F401, PLR1702, PLC2801, SIM117

import sys
from pathlib import Path

from tatsu.buffering import Buffer
from tatsu.parsing import Parser
from tatsu.parsing import tatsumasu
from tatsu.parsing import leftrec, nomemo, isname
from tatsu.infos import ParserConfig
from tatsu.util import re, generic_main


KEYWORDS: set[str] = set()


class Buffer(Buffer):
    def __init__(self, text, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            owner=self,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments_re=None,
            eol_comments_re=None,
            keywords=KEYWORDS,
            start='source',
        )
        config = config.replace(**settings)

        super().__init__(text, config=config)


class Parser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            owner=self,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments_re=None,
            eol_comments_re=None,
            keywords=KEYWORDS,
            start='source',
        )
        config = config.replace(**settings)

        super().__init__(config=config)

    @tatsumasu()
    def _source_(self):
        self._module_()

    @tatsumasu()
    def _module_(self):
        self._sections_()

    @tatsumasu()
    def _sections_(self):

        def block0():
            self._section_()
        self._positive_closure(block0)

    @tatsumasu()
    def _section_(self):

        def block0():
            self._words_()
        self._positive_closure(block0)

    @tatsumasu()
    def _words_(self):

        def block0():
            self._word_()
        self._positive_closure(block0)

    @tatsumasu()
    def _word_(self):

        def block0():
            self._namer_()
        self._positive_closure(block0)

    @tatsumasu()
    def _namer_(self):
        with self._choice():
            with self._option():
                self._letter_()
            with self._option():
                self._digit_()
            with self._option():
                self._under_()
            self._error(
                'expecting one of: '
                "'_' <digit> <letter> <under> [0-9]"
                '[a-zA-Z]'
            )

    @tatsumasu()
    def _letter_(self):
        self._pattern('[a-zA-Z]')

    @tatsumasu()
    def _digit_(self):
        self._pattern('[0-9]')

    @tatsumasu()
    def _under_(self):
        self._token('_')


def main(filename, **kwargs):
    if not filename or filename == '-':
        text = sys.stdin.read()
    else:
        text = Path(filename).read_text()
    parser = Parser()
    return parser.parse(
        text,
        filename=filename,
        **kwargs,
    )


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, Parser, name='')
    data = asjson(ast)
    print(json.dumps(data, indent=2))

