[metadata]
name = zatso
version = 0.1.14
url = "http://github.com/jalanb/zatso"
description-file = README.md
download_url =  "https://github.com/jalanb/zatso/tarball/"
license = MIT License
author = "J Alan Brogan"
author_email = github@al-got-rhythm.net
description = " ䷃  ZatSo reads 竜 TatSu objects"
platforms = unix, linux

