source = module ;

shebang = '#!' command;

#! /usr/local/bin/bash -x

module
    =
    | functions {statement}*
    | statement
    ;

statement = words ;

command = type words;

type =
   | word
   | path
   ;

options = {option}+ ;

option =
   | word
   | path
   | long_option
   | short_option
   ;

long_option = '--' word ;

short_option = '-' letter ;

statements = {statement}+ ;

function = '{word}' '(' ')' '{' '{word}+' '}' ;

functions = {function}+ ;

words = {word}+ ;

word = /[a-zA-Z0-9_]+/ ;

# word = {namer}+ ;

paths = {path}+ ;

path = {pather}+ ;

pather = letter | digit | under | slash ;

namer = letter | digit | under ;

letter = (/[a-z]/ | /[A-Z]/ ) ;

letters = {letter}+ ;

digit = /[0-9]/ ;

digits = {digit}+ ;

under = '_' ;

slash = '/' ;
