source = {shebang} {module} ;

shebang = '#!' {command};

#! /usr/local/bin/bash -x


module
    =
    | functions {statement}*
    | statement
    ;

statement = 
    | {words}
    | {command} {options}
    ;

command = 
   | {word}
   | {path}
   ;

options = {option}+ ;

option =
   | {word}
   | {path}
   | {long_option}
   | {short_option}
   ;

long_option = '--' {word} ;

short_option = '-' {letter} ;

statements = {statement}* ;

function = '{word}' '(' ')' '{' '{word}+' '}' ;

functions = {function}+ ;

words = {word}+ ;

word = {namer}+ ;

paths = {path}+ ;

path = {pather}+ ;

pather = {namer} | {slash} ;

namer = letter | digit | under ;

letter = (/[a-z]/ | /[A-Z]/ ) ;

letters = {letter}+ ;

digit = /[0-9]/ ;

digits = {digit}+ ;

under = '_' ;

slash = '/' ;
