source = module ;

module = sections ;

sections = {section}+ ;

section = {words}+ ;

words = {word}+ ;

word = {namer}+ ;

namer = letter | digit | under ;

letter = /[a-zA-Z]/ ;

digit = /[0-9]/ ;

under = '_' ;

